blank_issues_enabled: true
contact_links:
  - name: Questions and help
    url: https://forum.domoticz.com/viewtopic.php?t=45132
    about: For general questions or help with the theme, please use the Domoticz forum thread instead of an issue.
