blank_issues_enabled: true
contact_links:
  - name: Questions and help
    url: https://www.domoticz.com/forum/viewtopic.php?f=8&t=24084
    about: For general questions or help with the theme, please use the Domoticz forum thread instead of an issue.
