/* Icons tab on core's Settings page: browse the Machinon icon pack shipped
   in iconpack/ (generated by images-machinon's dz-pack-build.py) and
   install, update or remove each icon in the Domoticz CustomImages DB via
   the core JSON API. State is re-derived from the server after every
   action, never bookkept client-side, so every operation is idempotent.
   Pack strings only ever reach the DOM via textContent. */

var ICONPACK = { state: [] }; /* [{base, name, description, idx|null, outdated}] */

function injectIconPackTab() {
    if ($("#iconPackTabButton").length) return;
    $('<li id="iconPackTabButton"><a data-target="#tabiconpack" data-toggle="tab" data-i18n="Icons">Icons</a></li>').insertBefore("#tabs > li.pull-right");
    $("#my-tab-content").append('<div class="tab-pane" id="tabiconpack"><section id="iconpack">Loading..</section></div>');
    $("#my-tab-content #iconpack").load("styles/" + themeFolder + "/iconsettings.html", initIconPack);
}

function initIconPack() {
    $("#iconpack").i18n();
    $("#iconpackSearch").on("input", renderIconPackGrid);
    $("#iconpackInstallAll").on("click", installAllPackIcons);
    refreshIconPack();
}

function packPreviewUrl(base, state) {
    return "styles/" + themeFolder + "/iconpack/" + base + "48_" + state + ".png";
}

function fetchPackJson(url, opts) {
    return fetch(url, Object.assign({ credentials: "include" }, opts))
        .then(function(r) {
            if (!r.ok) { throw new Error("HTTP " + r.status); }
            return r.json();
        });
}

function loadPackManifest() {
    return fetchPackJson("styles/" + themeFolder + "/iconpack/manifest.json", { cache: "no-cache" });
}

/* base -> {idx, title, description}, Base recovered from the served path
   (core: RootFile == CustomImages.Base, IconFile48On = "images/<Base>48_On.png") */
function installedPackIcons() {
    return fetchPackJson("json.htm?type=command&param=getcustomiconset").then(function(data) {
        var map = {};
        (data.result || []).forEach(function(ic) {
            var m = /^images\/(.+)48_On\.png$/.exec(ic.IconFile48On || "");
            if (m) { map[m[1]] = { idx: ic.idx, title: ic.Title, description: ic.Description }; }
        });
        return map;
    });
}

function refreshIconPack() {
    return Promise.all([loadPackManifest(), installedPackIcons()]).then(function(res) {
        var manifest = res[0], installed = res[1];
        return Promise.all(manifest.icons.map(function(icon) {
            var inst = installed[icon.base];
            if (!inst) {
                return Promise.resolve({ base: icon.base, name: icon.name,
                    description: icon.description, idx: null, outdated: false });
            }
            return packIconOutdated(icon, inst).then(function(outdated) {
                return { base: icon.base, name: icon.name,
                    description: icon.description, idx: inst.idx, outdated: outdated };
            });
        }));
    }).then(function(state) {
        ICONPACK.state = state;
        renderIconPackGrid();
    }).catch(function(e) {
        var grid = document.getElementById("iconpackGrid");
        if (grid) { grid.textContent = "Icon pack not found in this theme install (" + e.message + ")."; }
    });
}

/* The icons matching the current search: the set the grid shows AND the set
   the install-all button acts on (its toolbar placement implies exactly that). */
function visiblePackIcons() {
    var q = ($("#iconpackSearch").val() || "").toLowerCase();
    return ICONPACK.state.filter(function(ic) {
        return !q || (ic.base + " " + ic.name + " " + ic.description).toLowerCase().indexOf(q) !== -1;
    });
}

function renderIconPackGrid() {
    var grid = document.getElementById("iconpackGrid");
    if (!grid) return;
    var shown = visiblePackIcons();
    var installedCount = ICONPACK.state.filter(function(ic) { return ic.idx !== null; }).length;
    document.getElementById("iconpackCounter").textContent =
        installedCount + " of " + ICONPACK.state.length + " installed";
    var allBtn = document.getElementById("iconpackInstallAll");
    if (allBtn) {
        allBtn.textContent = shown.length === ICONPACK.state.length
            ? "Install / update all"
            : "Install / update shown (" + shown.length + ")";
    }
    grid.textContent = "";
    shown.forEach(function(ic) { grid.appendChild(buildIconPackCard(ic)); });
    if (!shown.length) { grid.textContent = "No icons match the search."; }
}

function buildIconPackCard(ic) {
    var card = document.createElement("div");
    card.className = "iconpack-card" + (ic.idx !== null ? " installed" : "");
    card.setAttribute("data-base", ic.base);

    var img = document.createElement("img");
    img.className = "iconpack-preview";
    img.src = packPreviewUrl(ic.base, "On");
    img.alt = ic.name;
    /* preview state: On by default (owner preference), hover shows Off
       (desktop), click/tap toggles it (touch) */
    var sticky = false, hover = false;
    function paint() { img.src = packPreviewUrl(ic.base, (sticky !== hover) ? "Off" : "On"); }
    img.addEventListener("mouseenter", function() { hover = true; paint(); });
    img.addEventListener("mouseleave", function() { hover = false; paint(); });
    img.addEventListener("click", function() { sticky = !sticky; paint(); });
    card.appendChild(img);

    var name = document.createElement("div");
    name.className = "iconpack-name";
    name.textContent = ic.name;
    card.appendChild(name);

    var desc = document.createElement("div");
    desc.className = "iconpack-desc";
    desc.textContent = ic.description;
    card.appendChild(desc);

    if (ic.idx !== null) {
        var chip = document.createElement("span");
        chip.className = "iconpack-chip";
        chip.textContent = "Installed";
        card.appendChild(chip);
    }

    var actions = document.createElement("div");
    actions.className = "iconpack-actions";
    actions.appendChild(iconPackButton(
        ic.idx === null ? "add" : (ic.outdated ? "refresh" : "add-disabled"), ic));
    actions.appendChild(iconPackButton(ic.idx === null ? "remove-disabled" : "remove", ic));
    card.appendChild(actions);
    return card;
}

function iconPackButton(kind, ic) {
    var btn = document.createElement("button");
    btn.type = "button";
    var img = document.createElement("img");
    img.alt = "";
    if (kind === "add" || kind === "add-disabled") {
        btn.className = "iconpack-add";
        img.src = "images/add.png";
        btn.title = kind === "add-disabled" ? "Installed and up to date" : "Install";
        if (kind === "add-disabled") { btn.disabled = true; }
        else { btn.addEventListener("click", function() { installPackIcon(ic); }); }
    } else if (kind === "refresh") {
        btn.className = "iconpack-add";
        img.src = "images/machinon/refresh.png";
        btn.title = "Update available: reinstall";
        btn.addEventListener("click", function() { installPackIcon(ic); });
    } else {
        btn.className = "iconpack-remove";
        img.src = "images/remove.png";
        btn.title = kind === "remove-disabled" ? "Not installed" : "Remove";
        if (kind === "remove-disabled") { btn.disabled = true; }
        else { btn.addEventListener("click", function() { removePackIcon(ic); }); }
    }
    btn.appendChild(img);
    return btn;
}

function bytesEqual(a, b) {
    if (a.byteLength !== b.byteLength) return false;
    var x = new Uint8Array(a), y = new Uint8Array(b);
    for (var i = 0; i < x.length; i++) { if (x[i] !== y[i]) return false; }
    return true;
}

function fetchPackBytes(url) {
    return fetch(url, { cache: "no-cache", credentials: "include" }).then(function(r) {
        if (!r.ok) { throw new Error("HTTP " + r.status); }
        return r.arrayBuffer();
    });
}

/* Outdated = shipped art differs from the served DB art, or metadata drifted.
   The pack's 16px base derives from the On master, so On+Off covers art. */
function packIconOutdated(icon, installed) {
    if (installed.title !== icon.name || installed.description !== icon.description) {
        return Promise.resolve(true);
    }
    return Promise.all([
        fetchPackBytes(packPreviewUrl(icon.base, "On")),
        fetchPackBytes("images/" + icon.base + "48_On.png"),
        fetchPackBytes(packPreviewUrl(icon.base, "Off")),
        fetchPackBytes("images/" + icon.base + "48_Off.png")
    ]).then(function(b) {
        return !bytesEqual(b[0], b[1]) || !bytesEqual(b[2], b[3]);
    }).catch(function() { return false; }); /* unreadable art: no false update nag */
}

function uploadPackZip(base) {
    return fetch("styles/" + themeFolder + "/iconpack/" + base + ".zip",
        { cache: "no-cache", credentials: "include" })
        .then(function(r) {
            if (!r.ok) { throw new Error("zip fetch HTTP " + r.status); }
            return r.blob();
        })
        .then(function(blob) {
            var fd = new FormData();
            fd.append("file", blob, base + ".zip");
            return fetch("json.htm?type=command&param=uploadcustomicon",
                { method: "POST", body: fd, credentials: "include" });
        })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.status !== "OK") { throw new Error(data.error || "upload failed"); }
        });
}

function installPackIcon(ic) {
    return uploadPackZip(ic.base)
        .then(function() { generate_noty("success", ic.name + " installed", 3000); })
        .catch(function(e) { generate_noty("error", ic.name + ": " + e.message, 6000); })
        .then(refreshIconPack);
}

function devicesUsingPackIcon(idx) {
    return fetchPackJson("json.htm?type=command&param=getdevices&used=true&displayhidden=1")
        .then(function(data) {
            return (data.result || [])
                .filter(function(d) { return Number(d.CustomImage) === 100 + idx; })
                .map(function(d) { return d.Name; });
        });
}

function removePackIcon(ic) {
    devicesUsingPackIcon(ic.idx).then(function(users) {
        var msg = users.length
            ? 'Remove "' + ic.name + '"? Used by: ' + users.join(", ")
                + ". These devices will revert to their default icon."
            : 'Remove "' + ic.name + '" from the icon database?';
        bootbox.confirm({
            /* device names are user data: text only, never markup */
            message: $("<div>").text(msg),
            callback: function(ok) {
                if (!ok) return;
                fetchPackJson("json.htm?type=command&param=deletecustomicon&idx=" + ic.idx)
                    .then(function() { generate_noty("success", ic.name + " removed", 3000); })
                    .catch(function() { generate_noty("error", "Could not remove " + ic.name, 6000); })
                    .then(refreshIconPack);
            }
        });
    });
}

/* Sequential on purpose: each upload is a SQLite write plus blob extraction;
   parallel uploads invite lock contention. */
function installAllPackIcons() {
    var pool = visiblePackIcons();
    var todo = pool.filter(function(ic) { return ic.idx === null || ic.outdated; });
    var current = pool.length - todo.length;
    if (!todo.length) {
        generate_noty("success", "All " + pool.length + " shown pack icons are installed and current", 3000);
        return;
    }
    var added = 0, updated = 0, failures = [];
    var chain = Promise.resolve();
    todo.forEach(function(ic, i) {
        chain = chain.then(function() {
            generate_noty("information", "Installing " + (i + 1) + "/" + todo.length + ": " + ic.name, 1000);
            return uploadPackZip(ic.base)
                .then(function() { if (ic.idx === null) { added++; } else { updated++; } })
                .catch(function(e) { failures.push(ic.name + " (" + e.message + ")"); });
        });
    });
    chain.then(function() {
        var msg = added + " installed, " + updated + " updated, " + current + " already current";
        if (failures.length) { generate_noty("error", msg + "; failed: " + failures.join(", "), 8000); }
        else { generate_noty("success", msg, 5000); }
        refreshIconPack();
    });
}
