/* Icons tab on core's Settings page: browse the Machinon icon pack shipped
   in iconpack/ (generated by images-machinon's dz-pack-build.py) and
   install, update or remove each icon in the Domoticz CustomImages DB via
   the core JSON API. State is re-derived from the server after every
   action, never bookkept client-side, so every operation is idempotent.
   Pack strings only ever reach the DOM via textContent. */

var ICONPACK = { state: [] }; /* [{base, name, description, idx|null, outdated}] */

function injectIconPackTab() {
    if ($("#iconPackTabButton").length) return;
    $('<li id="iconPackTabButton"><a data-target="#tabiconpack" data-toggle="tab" data-i18n="Icons">Icons</a></li>').insertBefore("#tabs > li.pull-right");
    $("#my-tab-content").append('<div class="tab-pane" id="tabiconpack"><section id="iconpack">Loading..</section></div>');
    $("#my-tab-content #iconpack").load("styles/" + themeFolder + "/iconsettings.html", initIconPack);
}

function initIconPack() {
    $("#iconpack").i18n();
    $("#iconpackSearch").on("input", renderIconPackGrid);
    $("#iconpackInstallAll").on("click", installAllPackIcons);
    refreshIconPack();
}

function packPreviewUrl(base, state) {
    return "styles/" + themeFolder + "/iconpack/" + base + "48_" + state + ".png";
}

function fetchPackJson(url, opts) {
    return fetch(url, Object.assign({ credentials: "include" }, opts))
        .then(function(r) {
            if (!r.ok) { throw new Error("HTTP " + r.status); }
            return r.json();
        });
}

function loadPackManifest() {
    return fetchPackJson("styles/" + themeFolder + "/iconpack/manifest.json", { cache: "no-cache" });
}

/* base -> {idx, title, description}, Base recovered from the served path
   (core: RootFile == CustomImages.Base, IconFile48On = "images/<Base>48_On.png") */
function installedPackIcons() {
    return fetchPackJson("json.htm?type=command&param=getcustomiconset").then(function(data) {
        var map = {};
        (data.result || []).forEach(function(ic) {
            var m = /^images\/(.+)48_On\.png$/.exec(ic.IconFile48On || "");
            if (m) { map[m[1]] = { idx: ic.idx, title: ic.Title, description: ic.Description }; }
        });
        return map;
    });
}

function refreshIconPack() {
    return Promise.all([loadPackManifest(), installedPackIcons()]).then(function(res) {
        var manifest = res[0], installed = res[1];
        return Promise.all(manifest.icons.map(function(icon) {
            var inst = installed[icon.base];
            if (!inst) {
                return Promise.resolve({ base: icon.base, name: icon.name,
                    description: icon.description, idx: null, outdated: false });
            }
            return packIconOutdated(icon, inst).then(function(outdated) {
                return { base: icon.base, name: icon.name,
                    description: icon.description, idx: inst.idx, outdated: outdated };
            });
        }));
    }).then(function(state) {
        ICONPACK.state = state;
        renderIconPackGrid();
    }).catch(function(e) {
        var grid = document.getElementById("iconpackGrid");
        if (grid) { grid.textContent = "Icon pack not found in this theme install (" + e.message + ")."; }
    });
}

function renderIconPackGrid() {
    var grid = document.getElementById("iconpackGrid");
    if (!grid) return;
    var q = ($("#iconpackSearch").val() || "").toLowerCase();
    var shown = ICONPACK.state.filter(function(ic) {
        return !q || (ic.base + " " + ic.name + " " + ic.description).toLowerCase().indexOf(q) !== -1;
    });
    var installedCount = ICONPACK.state.filter(function(ic) { return ic.idx !== null; }).length;
    document.getElementById("iconpackCounter").textContent =
        installedCount + " of " + ICONPACK.state.length + " installed";
    grid.textContent = "";
    shown.forEach(function(ic) { grid.appendChild(buildIconPackCard(ic)); });
    if (!shown.length) { grid.textContent = "No icons match the search."; }
}

function buildIconPackCard(ic) {
    var card = document.createElement("div");
    card.className = "iconpack-card" + (ic.idx !== null ? " installed" : "");
    card.setAttribute("data-base", ic.base);

    var img = document.createElement("img");
    img.className = "iconpack-preview";
    img.src = packPreviewUrl(ic.base, "Off");
    img.alt = ic.name;
    /* preview state: hover shows On (desktop), click/tap toggles it (touch) */
    var sticky = false, hover = false;
    function paint() { img.src = packPreviewUrl(ic.base, (sticky !== hover) ? "On" : "Off"); }
    img.addEventListener("mouseenter", function() { hover = true; paint(); });
    img.addEventListener("mouseleave", function() { hover = false; paint(); });
    img.addEventListener("click", function() { sticky = !sticky; paint(); });
    card.appendChild(img);

    var name = document.createElement("div");
    name.className = "iconpack-name";
    name.textContent = ic.name;
    card.appendChild(name);

    var desc = document.createElement("div");
    desc.className = "iconpack-desc";
    desc.textContent = ic.description;
    card.appendChild(desc);

    if (ic.idx !== null) {
        var chip = document.createElement("span");
        chip.className = "iconpack-chip";
        chip.textContent = "Installed";
        card.appendChild(chip);
    }

    var actions = document.createElement("div");
    actions.className = "iconpack-actions";
    actions.appendChild(iconPackButton(
        ic.idx === null ? "add" : (ic.outdated ? "refresh" : "add-disabled"), ic));
    actions.appendChild(iconPackButton(ic.idx === null ? "remove-disabled" : "remove", ic));
    card.appendChild(actions);
    return card;
}

function iconPackButton(kind, ic) {
    var btn = document.createElement("button");
    btn.type = "button";
    var img = document.createElement("img");
    img.alt = "";
    if (kind === "add" || kind === "add-disabled") {
        btn.className = "iconpack-add";
        img.src = "images/add.png";
        btn.title = kind === "add-disabled" ? "Installed and up to date" : "Install";
        if (kind === "add-disabled") { btn.disabled = true; }
        else { btn.addEventListener("click", function() { installPackIcon(ic); }); }
    } else if (kind === "refresh") {
        btn.className = "iconpack-add";
        img.src = "images/machinon/refresh.png";
        btn.title = "Update available: reinstall";
        btn.addEventListener("click", function() { installPackIcon(ic); });
    } else {
        btn.className = "iconpack-remove";
        img.src = "images/remove.png";
        btn.title = kind === "remove-disabled" ? "Not installed" : "Remove";
        if (kind === "remove-disabled") { btn.disabled = true; }
        else { btn.addEventListener("click", function() { removePackIcon(ic); }); }
    }
    btn.appendChild(img);
    return btn;
}

/* Implemented in the actions task; harmless stubs so the skeleton renders. */
function packIconOutdated(icon, installed) { return Promise.resolve(false); }
function installPackIcon(ic) {}
function removePackIcon(ic) {}
function installAllPackIcons() {}
