#!/usr/bin/env bash
# Release-build flattener for the theme's CSS @import chain.
#
# WHY: task-9 perf audit found the @import chain in custom.css serializes one
# full round trip before its children start downloading (measured ~1019 ms
# child-start on Fast 3G vs ~200 ms for custom.css itself), plus turns one
# page load into 26+ separate HTTP requests. Source stays modular (one
# @import per leaf CSS file, see the ONE-LEVEL IMPORT RULE comment at the top
# of custom.css) because that is easiest to develop and review. This script
# recursively inlines that whole chain, depth-first in source order, into a
# single flat dist/custom.css for release artifacts, which is what actually
# removes the request fan-out for real users. Source and dist intentionally
# diverge: never hand-edit dist/custom.css, it is regenerated by this script.
#
# Usage:
#   scripts/build-dist.sh          build dist/custom.css
#   scripts/build-dist.sh --check  verify every @import in the chain resolves
#                                   to a real file; do not write any output
#
# -e/-o pipefail matter here because the future GH Actions release workflow
# will trust this script's exit code: any failed command, including a failed
# write of the output file, must surface as a non-zero exit rather than a
# success message over a broken artifact.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT_DIR="$(pwd)"
ROOT_FILE="custom.css"
OUT_FILE="dist/custom.css"

CHECK_ONLY=0
if [ "${1:-}" = "--check" ]; then
  CHECK_ONLY=1
fi

IMPORT_COUNT=0
# Space-separated list of relpaths already visited, used for cycle detection.
# NOTE: this is a seen-set, not an ancestor stack, so a legitimate diamond
# (two files importing the same third file) would also be rejected, with a
# misleading "circular" message. Latent by design: the source tree is one
# level deep (ONE-LEVEL IMPORT RULE in custom.css), where no diamond can
# exist, and double-inlining a file would silently change the cascade, so
# rejecting any re-visit is the safe behavior here.
VISITED=""

# Blanks CSS /* ... */ comments (including ones spanning multiple lines) to
# spaces while preserving line count, so line-based @import detection below
# never matches text that only appears inside a comment (several files in
# this repo mention "@import" in prose, e.g. css/tables.css, css/logpage.css).
# Column position inside a line is not preserved exactly, only enough
# structure that a still-commented @import cannot appear at the start of a
# line; that is all the caller needs. Reads from stdin.
blank_comments() {
  awk '
    {
      line = $0
      out = ""
      i = 1
      n = length(line)
      while (i <= n) {
        if (incomment) {
          idx = index(substr(line, i), "*/")
          if (idx == 0) {
            out = out sprintf("%*s", n - i + 1, "")
            i = n + 1
          } else {
            blanklen = idx + 1
            out = out sprintf("%*s", blanklen, "")
            i += blanklen
            incomment = 0
          }
        } else {
          idx = index(substr(line, i), "/*")
          if (idx == 0) {
            out = out substr(line, i)
            i = n + 1
          } else {
            out = out substr(line, i, idx - 1) "  "
            i += idx - 1 + 2
            incomment = 1
          }
        }
      }
      print out
    }
  '
}

fail() {
  echo "build-dist: ERROR: $*" >&2
  exit 1
}

# The flat dist/custom.css is served from the theme root (styles/machinon/),
# but a one-level-deep source file (dir != ".", i.e. anything under css/,
# per the ONE-LEVEL IMPORT RULE) writes its url(../x) references relative to
# its own directory (css/). Once that content is inlined into the root-level
# flat file, an un-rebased url(../x) resolves one level too high (styles/x
# instead of styles/machinon/x) and every referenced font 404s. Strip exactly
# one leading ../ from such urls at inline time to rebase them. Two levels of
# ../../ cannot happen under the one-level rule today, so treat that as a
# corruption signal and fail loudly rather than mis-rewrite silently; leave
# data:, http(s):, absolute, and non-../ urls untouched.
rebase_relative_url() {
  local line="$1" relpath="$2"
  if printf '%s' "$line" | grep -Eq "url\\([\"']?\\.\\./\\.\\./"; then
    fail "two-level ../../ in url() at '$relpath' violates the ONE-LEVEL IMPORT RULE: $line"
  fi
  sed -E "s#url\\((['\"]?)\\.\\./#url(\\1#g" <<< "$line"
}

# Strips a leading UTF-8 byte-order mark from $1, if present, to stdout.
# A BOM is only meaningful as the first three bytes of a standalone HTTP
# resource (that is how a browser fetching one leaf CSS file today knows its
# encoding). Once a file is inlined mid-document by this script, its BOM is
# no longer resource-initial: it becomes an ordinary, non-whitespace
# character sitting between two rules. That corrupted the very first build
# of dist/custom.css (css/ionicons.min.css carries a BOM): the flat file's
# rule count came out one short of the sum of its parts, traced to that
# stray character eating the @font-face rule immediately after it. Every
# leaf file gets @charset "UTF-8" from custom.css already, so no inlined
# file needs its own BOM.
strip_bom() {
  local first3
  first3=$(head -c 3 "$1" | od -An -tx1 | tr -d ' \n')
  if [ "$first3" = "efbbbf" ]; then
    tail -c +4 "$1"
  else
    cat "$1"
  fi
}

# Recursively emits the flattened content of $1 (a path relative to the
# theme root) to stdout, inlining every @import it contains depth-first in
# source order. $2 is a human-readable chain string used in error messages.
inline_file() {
  local relpath="$1" chain="$2"
  local abspath="$ROOT_DIR/$relpath"

  if [ ! -f "$abspath" ]; then
    fail "import target not found: '$relpath' (chain: $chain)"
  fi
  case " $VISITED " in
    *" $relpath "*) fail "circular @import detected: '$relpath' (chain: $chain)" ;;
  esac
  VISITED="$VISITED $relpath"

  local dir
  dir=$(dirname "$relpath")

  local content
  content=$(strip_bom "$abspath")

  local blanked
  blanked=$(blank_comments <<< "$content")
  local -a blankedlines
  mapfile -t blankedlines <<< "$blanked"

  echo "/* ==== begin: $relpath ==== */"

  local lineno=0 rawline bline target mediaraw media resolved
  # Kept in a variable (not inlined into [[ =~ ]]) because bash's regex
  # parser trips over the literal parens/quotes/brackets in an inline
  # pattern; this form is the documented workaround. Matches
  # @import url("path"); or @import url('path') (media-query);
  local import_re="^[[:space:]]*@import[[:space:]]+url\\([[:space:]]*['\"]?([^'\"()]+)['\"]?[[:space:]]*\\)[[:space:]]*([^;]*);"
  while IFS= read -r rawline || [ -n "$rawline" ]; do
    lineno=$((lineno + 1))
    bline="${blankedlines[$((lineno - 1))]:-}"
    if [[ "$bline" =~ $import_re ]]; then
      target="${BASH_REMATCH[1]}"
      mediaraw="${BASH_REMATCH[2]}"
      media="$(echo "$mediaraw" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g')"
      IMPORT_COUNT=$((IMPORT_COUNT + 1))

      if [ "$dir" = "." ]; then
        resolved="$target"
      else
        resolved=$(realpath --relative-to="$ROOT_DIR" "$ROOT_DIR/$dir/$target" 2>/dev/null) \
          || fail "could not resolve import path '$target' relative to '$relpath'"
      fi

      if [ -n "$media" ]; then
        echo "@media $media {"
        inline_file "$resolved" "$chain -> $relpath"
        echo "}"
      else
        inline_file "$resolved" "$chain -> $relpath"
      fi
    elif [[ "$bline" =~ ^[[:space:]]*@import ]]; then
      # Fail loudly on any @import form the url() regex above does not
      # recognize (e.g. bare @import "path.css";). Passing such a line
      # through verbatim would silently ship a still-nested @import in the
      # "flat" release file, defeating the whole point of this script.
      fail "unrecognized @import syntax at $relpath:$lineno: '$rawline' (only @import url(\"...\") [media]; is supported)"
    elif [ "$dir" != "." ]; then
      rebase_relative_url "$rawline" "$relpath"
    else
      echo "$rawline"
    fi
  done <<< "$content"

  echo "/* ==== end: $relpath ==== */"
}

if [ "$CHECK_ONLY" -eq 1 ]; then
  inline_file "$ROOT_FILE" "$ROOT_FILE" > /dev/null
  echo "build-dist --check: OK, $IMPORT_COUNT @import(s) resolved from $ROOT_FILE"
  exit 0
fi

mkdir -p "$(dirname "$OUT_FILE")"
# Explicit writability probe (truncates the target) so a read-only dist/ or
# permission problem fails with this script's own message; failures during
# the write itself (e.g. disk full) are caught by set -e, which aborts
# before the success line below can print. The 2>/dev/null must come FIRST:
# redirections apply left to right, so putting it after > "$OUT_FILE" would
# let bash's own "Permission denied" line escape before stderr is silenced.
: 2>/dev/null > "$OUT_FILE" || fail "cannot write $OUT_FILE (permissions? read-only?)"
{
  echo "/* GENERATED FILE. Do not edit by hand."
  echo "   Produced by scripts/build-dist.sh, which flattens custom.css's @import"
  echo "   chain (26+ leaf files) into one file for release artifacts. See the"
  echo "   ONE-LEVEL IMPORT RULE comment at the top of custom.css for why the"
  echo "   chain is flattened here instead of shipped as-is: a nested @import"
  echo "   chain serializes an extra network round trip per level (task-9 perf"
  echo "   audit). Edit the source files under css/ and re-run this script;"
  echo "   never edit this file directly, your changes will be overwritten. */"
  inline_file "$ROOT_FILE" "$ROOT_FILE"
} > "$OUT_FILE"

echo "build-dist: wrote $OUT_FILE ($IMPORT_COUNT @import(s) inlined from $ROOT_FILE)"
